site_name:        StaggeredPoisson.jl
repo_url:         https://github.com/glwagner/StaggeredPoisson.jl
site_description: Documentation for StaggeredPoisson.jl
site_author:      Gregory Wagner
theme:            material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

nav:
  - Home: index.md
